name: AoC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: egordeev/adventofcode:python-3.10-hyperfine
    steps:
      - uses: actions/checkout@v2
      - name: Run all and compare
        run: |
          cp 2021/answers.txt answers.tmp.txt
          hyperfine --warmup 3 -r 10 'python 2021/all.py' | tee benchmark.txt
          echo "=== All Solutions ==="
          cat 2021/answers.txt
          cmp -s 2021/answers.txt answers.tmp.txt || exit 1
          echo "RUNTIME_BADGE=$(sed -n 's|Time.*\:\(.*Â±\).*\[.*|\1|p' benchmark.txt | xargs)" >> $GITHUB_ENV
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 13c6cac3c39702cdcb9cc169b66c3210
          filename: runtime-badge.json
          label: Runtime
          message: ${{ env.RUNTIME_BADGE }}
          color: orange